// THIS FILE IS AUTO-GENERATED BY scripts/generate-schema.ts
// DO NOT EDIT THIS FILE DIRECTLY!

import { allContentTypeConfigs } from '../content-types';
import { generateDrizzleSchemaComponents, type AllTables, type AllGeneratedRelations } from './generation-logic';
import type { AnySQLiteTable } from 'drizzle-orm/sqlite-core';
import type { Relations } from 'drizzle-orm';
import type { AnySQLiteColumn } from 'drizzle-orm/sqlite-core';
type TableWithId = AnySQLiteTable & { id: AnySQLiteColumn };

console.log("[Schema] Initializing generated schema...");

// Regenerate components within the scope of the final schema file
const { allTables, allGeneratedRelations } = generateDrizzleSchemaComponents(allContentTypeConfigs);

console.log("[Schema] Exporting tables and relations...");

// --- Auto-generated Exports (Tables and Relations) ---
export const users = allTables['users'] as TableWithId;
export const posts = allTables['posts'] as TableWithId;
export const categories = allTables['categories'] as TableWithId;
export const session = allTables['session'] as TableWithId;
export const account = allTables['account'] as TableWithId;
export const verification = allTables['verification'] as TableWithId;
export const categories_to_posts = allTables['categories_to_posts'];

export const usersRelations = allGeneratedRelations['usersRelations'];
export const postsRelations = allGeneratedRelations['postsRelations'];
export const categoriesRelations = allGeneratedRelations['categoriesRelations'];
export const sessionRelations = allGeneratedRelations['sessionRelations'];
export const accountRelations = allGeneratedRelations['accountRelations'];
export const verificationRelations = allGeneratedRelations['verificationRelations'];
export const categories_to_postsRelations = allGeneratedRelations['categories_to_postsRelations'];

console.log("[Schema] Defining final schema object...");

// --- Auto-generated Schema Object ---
export const schema = {
	users,
	posts,
	categories,
	session,
	account,
	verification,
	categories_to_posts,
	usersRelations,
	postsRelations,
	categoriesRelations,
	sessionRelations,
	accountRelations,
	verificationRelations,
	categories_to_postsRelations,
};

console.log("[Schema] Generation complete.");

// --- Type Helpers ---
export type Schema = typeof schema;
// Use the keys obtained during generation for accurate TableName/RelationName types
export type TableName = keyof Pick<typeof allTables, 'users' | 'posts' | 'categories' | 'session' | 'account' | 'verification' | 'categories_to_posts'>;
export type RelationName = keyof Pick<typeof allGeneratedRelations, 'usersRelations' | 'postsRelations' | 'categoriesRelations' | 'sessionRelations' | 'accountRelations' | 'verificationRelations' | 'categories_to_postsRelations'>;
